# Generated by Django 3.2.4 on 2021-07-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=200)),
                ('Orignal_price', models.IntegerField()),
                ('Discount_price', models.IntegerField()),
                ('Image_link', models.CharField(max_length=150)),
            ],
        ),
    ]
