# Generated by Django 3.2.4 on 2021-07-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommarceWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Discription',
            field=models.TextField(max_length=200),
        ),
    ]
